[build]
builder = "RAILPACK"

[deploy]
startCommand = "python otp_forwarder.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Yeh settings Railway par Google Chrome install karne ke liye zaroori hain
[build.nixpacks]
aptPackages = ["google-chrome-stable", "chromium-chromedriver"]
