[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python otp_forwarder.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Yeh section custom Linux environments mein Chrome aur Chromedriver auto-inject karega
[build.nixpacks]
pkgs = ["google-chrome", "chromium"]
